### ISSUE TITLE
Add seed data

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/browser-calls-laravel#1]
Overall this looked really good! Just one request - can you add the same seed data to this repo that we have in the Django and Rails repos?

Django: https://github.com/TwilioDevEd/browser-calls-django/blob/master/browser_calls/migrations/0002_create_sample_data.py
Rails: https://github.com/TwilioDevEd/browser-calls-rails/blob/master/db/seeds.rb

It's a little nicer experience for a developer if there are already some tickets in the dashboard for them to experiment with.

**Comment by jsantos17** [comment]
There's seed data! Refer to https://github.com/TwilioDevEd/browser-calls-laravel/blob/master/database/seeds/TicketSeeder.php

**Comment by atbaker** [comment]
Ah - I missed the seed data because it wasn't in the README. I'll update the README to include `php artisan db:seed`
