### ISSUE TITLE
When will you update the twilio JS SDK to version 2?

### ISSUE THREAD

**Issue by tariq-360synergytech** [TwilioDevEd/browser-calls-laravel#164]
The new Twilio SDK for JS is now call **Twilio Voice JavaScript**

will you guys update the JS in this project ?

**Comment by bld010** [comment]
Hi @tariq-360synergytech,  Twilio Developer Educator here. 
We will be updating this project to use v2 of the JS SDK (as well as update Capability Tokens to Access Tokens).  
If you're looking to get started in the meantime, you can check out the [JS SDK Quickstart for PHP & composer](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-php) or use the [JS SDK v1 to v2 Migration Guide](https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20) to help you use v2 with this specific repo.
