### ISSUE TITLE
Add links to Twilio account portal in .env.example

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/browser-calls-laravel#2]
When a new developer is setting the values in their `.env` file, it's nice to give them links to where they can find all their Twilio sids.

We should add those links as comments in the `.env.example` file. Here's an example:

https://github.com/TwilioDevEd/browser-calls-django/blob/master/.env_example

**Comment by atbaker** [comment]
I'll also take care of this one, @jsantos17 - I'd like to try and deploy this today if I can

**Comment by jsantos17** [comment]
Since you already added the comments we should probably close this :)
